// Author https://github.com/yegor-sytnyk/movies-list

export default [
    {
      email: "john.doe@example.com",
      firstName: "John",
      lastName: "Doe",
      customerDate: "2022-01-15",
      leadDate: "2021-12-01",
    },
    {
      email: "john.doe@example.com",
      firstName: "John",
      lastName: "Doe",
      customerDate: "2022-01-15",
      leadDate: "2021-12-01",
    },
    {
      email: "john.doe@example.com",
      firstName: "John",
      lastName: "Doe",
      customerDate: "2022-01-15",
      leadDate: "2021-12-01",
    },
    {
      email: "john.doe@example.com",
      firstName: "John",
      lastName: "Doe",
      customerDate: "2022-01-15",
      leadDate: "2021-12-01",
    },
    {
      email: "jane.doe@example.com",
      firstName: "Jane",
      lastName: "Doe",
      customerDate: "2022-02-20",
      leadDate: "2022-01-15",
    },
    {
      email: "jim.smith@example.com",
      firstName: "Jim",
      lastName: "Smith",
      customerDate: "2022-03-10",
      leadDate: "2022-02-05",
    },
    {
      email: "susan.jones@example.com",
      firstName: "Susan",
      lastName: "Jones",
      customerDate: "2022-04-18",
      leadDate: "2022-03-12",
    },
    {
      email: "michael.brown@example.com",
      firstName: "Michael",
      lastName: "Brown",
      customerDate: "2022-05-25",
      leadDate: "2022-04-20",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "linda.white@example.com",
      firstName: "Linda",
      lastName: "White",
      customerDate: "2022-06-30",
      leadDate: "2022-05-28",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "robert.johnson@example.com",
      firstName: "Robert",
      lastName: "Johnson",
      customerDate: "2022-07-04",
      leadDate: "2022-06-01",
    },
    {
      email: "patricia.davis@example.com",
      firstName: "Patricia",
      lastName: "Davis",
      customerDate: "2022-08-09",
      leadDate: "2022-07-05",
    },
    {
      email: "charles.martinez@example.com",
      firstName: "Charles",
      lastName: "Martinez",
      customerDate: "2022-09-14",
      leadDate: "2022-08-10",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
    {
      email: "barbara.garcia@example.com",
      firstName: "Barbara",
      lastName: "Garcia",
      customerDate: "2022-10-19",
      leadDate: "2022-09-15",
    },
  ];
  